version: 1.0
prototypes:
  - type: voltage
    model: volt1103
    manufacturer: vaporio
    protocol: emulator
    output:
      - type: voltage
        data_type: float
        unit:
          name: volts
          symbol: V
        precision: 5
        range:
          min: -10
          max: 10
