version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
        environment:
          DEBUG: true

    working_directory: /go/src/github.com/vapor-ware/synse-sdk

    environment:
      TEST_DIRECTORY: "gotest"

    steps:
      - checkout

      - restore_cache:
          keys:
            - vendor-{{ checksum "Gopkg.toml" }}-{{ checksum "Gopkg.lock" }}
            - vendor-{{ checksum "Gopkg.toml" }}

      - run:
          name: "Setup"
          command: |
            mkdir -p /tmp/$TEST_DIRECTORY

      - run:
          name: "Lint"
          command: |
            go get -u github.com/golang/lint/golint
            golint -set_exit_status sdk/... client/... examples/...

      - run:
          name: "Install Vendored Dependencies"
          command: |
            go get -v github.com/golang/dep/cmd/dep
            go install github.com/golang/dep/cmd/dep
            dep ensure -v

      - run:
          name: "Get Test JUnit Parser"
          command: |
            go get -v -u github.com/jstemmer/go-junit-report

      - run:
          name: "Test"
          command: |
            go test -v ./sdk 2>&1 | go-junit-report > /tmp/$TEST_DIRECTORY/report.xml

      - save_cache:
          when: on_success
          key: vendor-{{ checksum "Gopkg.toml" }}-{{ checksum "Gopkg.lock" }}
          paths:
            - vendor/

      - store_test_results:
          path: /tmp/$TEST_DIRECTORY
