version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
        environment:
          DEBUG: true

    working_directory: /go/src/github.com/vapor-ware/synse-sdk
    steps:
      - checkout

      - run:
          name: "Lint"
          command: |
            make lint

      - run:
          name: "Get Dependencies"
          command: |
            go get -v -t -d ./sdk

      - run:
          name: "Test"
          command: |
            go test -v ./sdk