version: 1
name: example-plugin
debug: true
network:
  type: unix
  address: example-plugin.sock
settings:
  read:
    interval: 100s
    buffer: 150
  write:
    interval: 100s
    buffer: 150
  transaction:
    ttl: 600s
