version: 1.0
locations:
  unknown:
    rack: unknown
    board: unknown
devices:
  - type: emulated-temperature
    model: emul8-temp
    instances:
      - id: 1
        location: unknown
        comment: first emulated temperature device
        info: CEC temp 1
      - id: 2
        location: unknown
        comment: second emulated temperature device
        info: CEC temp 2
      - id: 3
        location: unknown
        comment: third emulated temperature device
        info: CEC temp 3
