version: 1.0
prototypes:
  - type: emulated-led
    model: emul8-led
    manufacturer: vaporio
    protocol: emulator
    output:
      - type: led_state
        data_type: string
      - type: led_color
        data_type: string
