version: 1.0
prototypes:
  - type: emulated-temperature
    model: emul8-temp
    manufacturer: vaporio
    protocol: emulator
    output:
      - type: temperature
        data_type: float
        unit:
          name: celsius
          symbol: C
        precision: 2
        range:
          min: 0
          max: 100
