version: 1.0
type: temperature
model: temp2010
manufacturer: vaporio
protocol: emulator
output:
  - type: temperature
    unit:
      name: celsius
      symbol: C
    precision: 2
    range:
      min: 0
      max: 100