version: 1.0
type: voltage
model: volt1103

locations:
  r1b1:
    rack: rack-1
    board: board-1
  r1b2:
    rack: rack-1
    board: board-2
  r2b1:
    rack: rack-2
    board: board-1

devices:
  - id: 1
    location: r1b1
    comment: first emulated voltage device
  - id: 2
    location: r1b2
    comment: second emulated voltage device
  - id: 3
    location: r2b1
    comment: third emulated voltage device
